runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_files: www/js/script.js
  upload: www/js/script.js

- url: /
  static_files: www/css/style.css
  upload: www/css/style.css

- url: /
  static_files: www/images/1.gif
  upload: www/images/1.gif

- url: /
  static_files: www/audio/Canon.mp3
  upload: www/audio/Canon.mp3

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)